CREATE TABLE customers (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  home_branch_id TEXT,
  customer_code TEXT,
  full_name TEXT NOT NULL,
  name_search TEXT NOT NULL,
  phone TEXT NOT NULL,
  phone_normalized TEXT NOT NULL,
  email TEXT,
  email_normalized TEXT,
  address TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  registration_source TEXT NOT NULL DEFAULT 'STAFF' CHECK (registration_source IN ('STAFF', 'ADMIN', 'IMPORT', 'ONLINE')),
  registered_at TEXT NOT NULL,
  last_visit_at TEXT,
  total_visits_cached INTEGER NOT NULL DEFAULT 0 CHECK (total_visits_cached >= 0),
  total_spent_minor_cached INTEGER NOT NULL DEFAULT 0 CHECK (total_spent_minor_cached >= 0),
  created_by_user_id TEXT,
  updated_by_user_id TEXT,
  deactivated_at TEXT,
  deactivated_by_user_id TEXT,
  deactivation_reason TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
  FOREIGN KEY (home_branch_id) REFERENCES branches(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (deactivated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE (organization_id, phone_normalized)
);

CREATE TABLE vehicle_types (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_by_user_id TEXT,
  updated_by_user_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE (organization_id, code),
  UNIQUE (organization_id, name)
);

CREATE TABLE vehicles (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  vehicle_type_id TEXT NOT NULL,
  registration_number TEXT NOT NULL,
  registration_normalized TEXT NOT NULL,
  make TEXT,
  model TEXT,
  manufacturing_year INTEGER CHECK (manufacturing_year IS NULL OR manufacturing_year BETWEEN 1900 AND 2200),
  colour TEXT,
  fuel_type TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  total_washes_cached INTEGER NOT NULL DEFAULT 0 CHECK (total_washes_cached >= 0),
  last_wash_at TEXT,
  created_by_user_id TEXT,
  updated_by_user_id TEXT,
  deactivated_at TEXT,
  deactivated_by_user_id TEXT,
  deactivation_reason TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
  FOREIGN KEY (vehicle_type_id) REFERENCES vehicle_types(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (deactivated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE (organization_id, registration_normalized)
);
