CREATE TABLE services (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  service_kind TEXT NOT NULL CHECK (service_kind IN ('PRIMARY', 'ADD_ON')),
  base_price_minor INTEGER NOT NULL DEFAULT 0 CHECK (base_price_minor >= 0),
  estimated_duration_minutes INTEGER CHECK (estimated_duration_minutes IS NULL OR estimated_duration_minutes >= 0),
  is_taxable INTEGER NOT NULL DEFAULT 0 CHECK (is_taxable IN (0, 1)),
  tax_rate_basis_points INTEGER CHECK (tax_rate_basis_points IS NULL OR tax_rate_basis_points BETWEEN 0 AND 10000),
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_by_user_id TEXT,
  updated_by_user_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE (organization_id, code)
);

CREATE TABLE service_prices (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  service_id TEXT NOT NULL,
  vehicle_type_id TEXT NOT NULL,
  price_minor INTEGER NOT NULL CHECK (price_minor >= 0),
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  effective_from TEXT NOT NULL,
  effective_to TEXT,
  created_by_user_id TEXT,
  created_at TEXT NOT NULL,
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
  FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE RESTRICT,
  FOREIGN KEY (vehicle_type_id) REFERENCES vehicle_types(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE UNIQUE INDEX ux_service_prices_active ON service_prices (service_id, vehicle_type_id) WHERE is_active = 1 AND effective_to IS NULL;

CREATE TABLE wash_jobs (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  branch_id TEXT NOT NULL,
  job_reference TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  vehicle_id TEXT NOT NULL,
  assigned_user_id TEXT NOT NULL,
  customer_name_snapshot TEXT NOT NULL,
  customer_phone_snapshot TEXT NOT NULL,
  vehicle_registration_snapshot TEXT NOT NULL,
  vehicle_type_name_snapshot TEXT NOT NULL,
  vehicle_make_snapshot TEXT,
  vehicle_model_snapshot TEXT,
  status TEXT NOT NULL DEFAULT 'WAITING' CHECK (status IN ('DRAFT', 'WAITING', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'CANCELLED')),
  payment_status TEXT NOT NULL DEFAULT 'PENDING' CHECK (payment_status IN ('PENDING', 'PARTIALLY_PAID', 'PAID', 'REFUNDED', 'CANCELLED')),
  subtotal_minor INTEGER NOT NULL DEFAULT 0 CHECK (subtotal_minor >= 0),
  coupon_discount_minor INTEGER NOT NULL DEFAULT 0 CHECK (coupon_discount_minor >= 0),
  referral_discount_minor INTEGER NOT NULL DEFAULT 0 CHECK (referral_discount_minor >= 0),
  reward_discount_minor INTEGER NOT NULL DEFAULT 0 CHECK (reward_discount_minor >= 0),
  manual_discount_minor INTEGER NOT NULL DEFAULT 0 CHECK (manual_discount_minor >= 0),
  total_discount_minor INTEGER NOT NULL DEFAULT 0 CHECK (total_discount_minor >= 0),
  taxable_amount_minor INTEGER NOT NULL DEFAULT 0 CHECK (taxable_amount_minor >= 0),
  tax_minor INTEGER NOT NULL DEFAULT 0 CHECK (tax_minor >= 0),
  rounding_minor INTEGER NOT NULL DEFAULT 0,
  total_amount_minor INTEGER NOT NULL DEFAULT 0 CHECK (total_amount_minor >= 0),
  paid_amount_minor INTEGER NOT NULL DEFAULT 0 CHECK (paid_amount_minor >= 0),
  refunded_amount_minor INTEGER NOT NULL DEFAULT 0 CHECK (refunded_amount_minor >= 0),
  balance_minor INTEGER NOT NULL DEFAULT 0 CHECK (balance_minor >= 0),
  tax_rate_basis_points INTEGER CHECK (tax_rate_basis_points IS NULL OR tax_rate_basis_points BETWEEN 0 AND 10000),
  currency_code TEXT NOT NULL DEFAULT 'INR',
  started_at TEXT,
  paused_at TEXT,
  completed_at TEXT,
  cancelled_at TEXT,
  total_active_seconds INTEGER NOT NULL DEFAULT 0 CHECK (total_active_seconds >= 0),
  total_paused_seconds INTEGER NOT NULL DEFAULT 0 CHECK (total_paused_seconds >= 0),
  mandatory_photo_verified INTEGER NOT NULL DEFAULT 0 CHECK (mandatory_photo_verified IN (0, 1)),
  mandatory_location_verified INTEGER NOT NULL DEFAULT 0 CHECK (mandatory_location_verified IN (0, 1)),
  business_location_status TEXT CHECK (business_location_status IS NULL OR business_location_status IN ('AT_BUSINESS_LOCATION', 'OUTSIDE_BUSINESS_LOCATION', 'COULD_NOT_VERIFY', 'OVERRIDDEN')),
  notes TEXT,
  cancellation_reason TEXT,
  manual_discount_reason TEXT,
  created_by_user_id TEXT NOT NULL,
  updated_by_user_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
  FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE RESTRICT,
  FOREIGN KEY (assigned_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE (organization_id, job_reference),
  CHECK (total_discount_minor = coupon_discount_minor + referral_discount_minor + reward_discount_minor + manual_discount_minor),
  CHECK (total_discount_minor <= subtotal_minor),
  CHECK (total_amount_minor = subtotal_minor - total_discount_minor + tax_minor + rounding_minor),
  CHECK (balance_minor = CASE WHEN total_amount_minor - paid_amount_minor + refunded_amount_minor < 0 THEN 0 ELSE total_amount_minor - paid_amount_minor + refunded_amount_minor END),
  CHECK (status <> 'CANCELLED' OR cancellation_reason IS NOT NULL)
);

CREATE TABLE wash_job_items (
  id TEXT PRIMARY KEY,
  wash_job_id TEXT NOT NULL,
  service_id TEXT,
  item_kind TEXT NOT NULL CHECK (item_kind IN ('PRIMARY', 'ADD_ON')),
  service_code_snapshot TEXT,
  service_name_snapshot TEXT NOT NULL,
  description_snapshot TEXT,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price_minor INTEGER NOT NULL CHECK (unit_price_minor >= 0),
  line_subtotal_minor INTEGER NOT NULL CHECK (line_subtotal_minor >= 0),
  discount_minor INTEGER NOT NULL DEFAULT 0 CHECK (discount_minor >= 0),
  taxable_amount_minor INTEGER NOT NULL DEFAULT 0 CHECK (taxable_amount_minor >= 0),
  tax_rate_basis_points INTEGER CHECK (tax_rate_basis_points IS NULL OR tax_rate_basis_points BETWEEN 0 AND 10000),
  tax_minor INTEGER NOT NULL DEFAULT 0 CHECK (tax_minor >= 0),
  line_total_minor INTEGER NOT NULL CHECK (line_total_minor >= 0),
  estimated_duration_minutes INTEGER,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  FOREIGN KEY (wash_job_id) REFERENCES wash_jobs(id) ON DELETE RESTRICT,
  FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL,
  CHECK (line_subtotal_minor = quantity * unit_price_minor),
  CHECK (discount_minor <= line_subtotal_minor),
  CHECK (line_total_minor = line_subtotal_minor - discount_minor + tax_minor)
);

CREATE UNIQUE INDEX ux_wash_job_primary_service ON wash_job_items (wash_job_id) WHERE item_kind = 'PRIMARY';
