CREATE TABLE payments (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  branch_id TEXT NOT NULL,
  wash_job_id TEXT NOT NULL,
  payment_reference TEXT,
  transaction_type TEXT NOT NULL DEFAULT 'PAYMENT' CHECK (transaction_type IN ('PAYMENT', 'ADJUSTMENT')),
  amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
  payment_method TEXT NOT NULL CHECK (payment_method IN ('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER')),
  status TEXT NOT NULL CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED')),
  external_transaction_reference TEXT,
  paid_at TEXT,
  received_by_user_id TEXT NOT NULL,
  notes TEXT,
  idempotency_key TEXT,
  created_at TEXT NOT NULL,
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT,
  FOREIGN KEY (wash_job_id) REFERENCES wash_jobs(id) ON DELETE RESTRICT,
  FOREIGN KEY (received_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  UNIQUE (organization_id, idempotency_key)
);

CREATE TABLE refunds (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  branch_id TEXT NOT NULL,
  payment_id TEXT NOT NULL,
  wash_job_id TEXT NOT NULL,
  amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
  status TEXT NOT NULL CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED')),
  reason TEXT NOT NULL CHECK (length(trim(reason)) > 0),
  external_refund_reference TEXT,
  approved_by_user_id TEXT NOT NULL,
  processed_at TEXT,
  idempotency_key TEXT,
  created_at TEXT NOT NULL,
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT,
  FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT,
  FOREIGN KEY (wash_job_id) REFERENCES wash_jobs(id) ON DELETE RESTRICT,
  FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  UNIQUE (organization_id, idempotency_key)
);

CREATE TABLE invoices (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  branch_id TEXT NOT NULL,
  wash_job_id TEXT NOT NULL,
  invoice_number TEXT NOT NULL,
  revision_number INTEGER NOT NULL DEFAULT 0 CHECK (revision_number >= 0),
  invoice_status TEXT NOT NULL DEFAULT 'ISSUED' CHECK (invoice_status IN ('DRAFT', 'ISSUED', 'REVISED', 'CANCELLED')),
  business_name_snapshot TEXT NOT NULL,
  business_logo_asset_id TEXT,
  business_address_snapshot TEXT,
  business_phone_snapshot TEXT,
  business_whatsapp_snapshot TEXT,
  business_email_snapshot TEXT,
  tax_registration_snapshot TEXT,
  customer_name_snapshot TEXT NOT NULL,
  customer_phone_snapshot TEXT NOT NULL,
  customer_email_snapshot TEXT,
  customer_address_snapshot TEXT,
  vehicle_registration_snapshot TEXT NOT NULL,
  vehicle_type_snapshot TEXT,
  vehicle_make_snapshot TEXT,
  vehicle_model_snapshot TEXT,
  wash_started_at_snapshot TEXT,
  wash_completed_at_snapshot TEXT,
  wash_duration_seconds_snapshot INTEGER CHECK (wash_duration_seconds_snapshot IS NULL OR wash_duration_seconds_snapshot >= 0),
  staff_name_snapshot TEXT,
  subtotal_minor INTEGER NOT NULL CHECK (subtotal_minor >= 0),
  discount_minor INTEGER NOT NULL CHECK (discount_minor >= 0),
  taxable_amount_minor INTEGER NOT NULL CHECK (taxable_amount_minor >= 0),
  tax_minor INTEGER NOT NULL CHECK (tax_minor >= 0),
  rounding_minor INTEGER NOT NULL DEFAULT 0,
  total_minor INTEGER NOT NULL CHECK (total_minor >= 0),
  paid_minor INTEGER NOT NULL CHECK (paid_minor >= 0),
  balance_minor INTEGER NOT NULL CHECK (balance_minor >= 0),
  currency_code TEXT NOT NULL,
  coupon_code_snapshot TEXT,
  referral_code_snapshot TEXT,
  referral_message_snapshot TEXT,
  payment_method_summary TEXT,
  payment_status_snapshot TEXT NOT NULL,
  thank_you_message_snapshot TEXT,
  terms_snapshot TEXT,
  footer_snapshot TEXT,
  invoice_snapshot_json TEXT NOT NULL,
  pdf_asset_id TEXT,
  public_access_token_hash TEXT,
  public_access_expires_at TEXT,
  issued_at TEXT,
  issued_by_user_id TEXT,
  revised_from_invoice_id TEXT,
  created_at TEXT NOT NULL,
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT,
  FOREIGN KEY (wash_job_id) REFERENCES wash_jobs(id) ON DELETE RESTRICT,
  FOREIGN KEY (business_logo_asset_id) REFERENCES file_assets(id) ON DELETE SET NULL,
  FOREIGN KEY (pdf_asset_id) REFERENCES file_assets(id) ON DELETE SET NULL,
  FOREIGN KEY (issued_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  FOREIGN KEY (revised_from_invoice_id) REFERENCES invoices(id) ON DELETE RESTRICT,
  UNIQUE (organization_id, invoice_number, revision_number),
  UNIQUE (wash_job_id, revision_number),
  CHECK (discount_minor <= subtotal_minor),
  CHECK (total_minor = subtotal_minor - discount_minor + tax_minor + rounding_minor)
);

CREATE TABLE invoice_items (
  id TEXT PRIMARY KEY,
  invoice_id TEXT NOT NULL,
  source_wash_job_item_id TEXT,
  item_kind TEXT NOT NULL CHECK (item_kind IN ('PRIMARY', 'ADD_ON', 'ADJUSTMENT')),
  item_code TEXT,
  item_name TEXT NOT NULL,
  description TEXT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price_minor INTEGER NOT NULL CHECK (unit_price_minor >= 0),
  subtotal_minor INTEGER NOT NULL CHECK (subtotal_minor >= 0),
  discount_minor INTEGER NOT NULL DEFAULT 0 CHECK (discount_minor >= 0),
  tax_rate_basis_points INTEGER,
  tax_minor INTEGER NOT NULL DEFAULT 0 CHECK (tax_minor >= 0),
  total_minor INTEGER NOT NULL CHECK (total_minor >= 0),
  display_order INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE RESTRICT,
  FOREIGN KEY (source_wash_job_item_id) REFERENCES wash_job_items(id) ON DELETE SET NULL,
  CHECK (subtotal_minor = quantity * unit_price_minor),
  CHECK (total_minor = subtotal_minor - discount_minor + tax_minor)
);

CREATE TRIGGER tr_payments_no_update BEFORE UPDATE ON payments BEGIN SELECT RAISE(ABORT, 'payments are append-only'); END;
CREATE TRIGGER tr_payments_no_delete BEFORE DELETE ON payments BEGIN SELECT RAISE(ABORT, 'payments are append-only'); END;
CREATE TRIGGER tr_refunds_no_update BEFORE UPDATE ON refunds BEGIN SELECT RAISE(ABORT, 'refunds are append-only'); END;
CREATE TRIGGER tr_refunds_no_delete BEFORE DELETE ON refunds BEGIN SELECT RAISE(ABORT, 'refunds are append-only'); END;
CREATE TRIGGER tr_invoices_issued_no_update BEFORE UPDATE ON invoices WHEN OLD.invoice_status <> 'DRAFT' BEGIN SELECT RAISE(ABORT, 'issued invoices are immutable; create a revision'); END;
CREATE TRIGGER tr_invoices_no_delete BEFORE DELETE ON invoices BEGIN SELECT RAISE(ABORT, 'invoices are immutable'); END;
CREATE TRIGGER tr_invoice_items_no_update BEFORE UPDATE ON invoice_items BEGIN SELECT RAISE(ABORT, 'invoice items are immutable'); END;
CREATE TRIGGER tr_invoice_items_no_delete BEFORE DELETE ON invoice_items BEGIN SELECT RAISE(ABORT, 'invoice items are immutable'); END;
