import {
  formatMinorForDisplay,
  formatReportLabel,
  type ReportColumn,
} from "@washpro/domain";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

function printable(value: unknown): string {
  return String(value ?? "—")
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/gu, "?");
}

function shorten(value: unknown, limit: number): string {
  const text = printable(value);
  return text.length <= limit
    ? text
    : `${text.slice(0, Math.max(1, limit - 1))}…`.replace("…", ".");
}

function displayCell(
  row: Record<string, unknown>,
  column: ReportColumn,
  currency: string,
): unknown {
  return column.type === "currencyMinor"
    ? formatMinorForDisplay(row[column.key], currency)
    : row[column.key];
}

export async function buildReportPdf(input: {
  readonly columns: readonly ReportColumn[];
  readonly currency: string;
  readonly from: string;
  readonly report: string;
  readonly rows: readonly Record<string, unknown>[];
  readonly to: string;
}): Promise<Uint8Array> {
  const document = await PDFDocument.create();
  document.setTitle(`WashPro ${input.report} report`);
  document.setCreator("WashPro");
  const regular = await document.embedFont(StandardFonts.Helvetica);
  const bold = await document.embedFont(StandardFonts.HelveticaBold);
  const navy = rgb(7 / 255, 26 / 255, 46 / 255);
  const blue = rgb(11 / 255, 134 / 255, 211 / 255);
  const ink = rgb(32 / 255, 48 / 255, 65 / 255);
  const muted = rgb(100 / 255, 119 / 255, 138 / 255);
  const line = rgb(220 / 255, 230 / 255, 238 / 255);
  const columns = input.columns;
  const width = 842;
  const height = 595;
  const margin = 42;
  const usable = width - margin * 2;
  const columnWidth = columns.length === 0 ? usable : usable / columns.length;
  let page = document.addPage([width, height]);
  let y = height - margin;

  const drawHeader = () => {
    page.drawRectangle({
      color: navy,
      height: 74,
      width,
      x: 0,
      y: height - 74,
    });
    page.drawText("W", {
      color: rgb(1, 1, 1),
      font: bold,
      size: 22,
      x: margin,
      y: height - 45,
    });
    page.drawText("WASHPRO", {
      color: rgb(1, 1, 1),
      font: bold,
      size: 10,
      x: margin + 30,
      y: height - 35,
    });
    page.drawText(`${printable(input.report).toUpperCase()} REPORT`, {
      color: rgb(181 / 255, 222 / 255, 247 / 255),
      font: regular,
      size: 8,
      x: margin + 30,
      y: height - 49,
    });
    page.drawText(`${input.from} to ${input.to}`, {
      color: rgb(1, 1, 1),
      font: bold,
      size: 10,
      x: width - margin - 135,
      y: height - 40,
    });
    y = height - 102;
    page.drawText(
      `${input.rows.length} record${input.rows.length === 1 ? "" : "s"}`,
      { color: muted, font: regular, size: 8, x: margin, y },
    );
    y -= 22;
    if (columns.length > 0) {
      page.drawRectangle({
        color: rgb(232 / 255, 245 / 255, 253 / 255),
        height: 25,
        width: usable,
        x: margin,
        y: y - 7,
      });
      columns.forEach((column, index) =>
        page.drawText(
          shorten(formatReportLabel(column.key).toUpperCase(), 18),
          {
            color: blue,
            font: bold,
            size: 6.5,
            x: margin + index * columnWidth + 5,
            y,
          },
        ),
      );
      y -= 24;
    }
  };

  drawHeader();
  if (input.rows.length === 0) {
    page.drawText("No data is available for this report range.", {
      color: muted,
      font: regular,
      size: 11,
      x: margin,
      y: y - 25,
    });
  }
  for (const row of input.rows) {
    if (y < 55) {
      page = document.addPage([width, height]);
      drawHeader();
    }
    columns.forEach((column, index) =>
      page.drawText(
        shorten(
          displayCell(row, column, input.currency),
          Math.max(8, Math.floor(columnWidth / 6)),
        ),
        {
          color: ink,
          font: regular,
          size: 7,
          x: margin + index * columnWidth + 5,
          y,
        },
      ),
    );
    page.drawLine({
      color: line,
      end: { x: width - margin, y: y - 7 },
      start: { x: margin, y: y - 7 },
      thickness: 0.5,
    });
    y -= 21;
  }
  for (const [index, current] of document.getPages().entries()) {
    current.drawText(
      `Generated by WashPro  |  Page ${index + 1} of ${document.getPageCount()}`,
      { color: muted, font: regular, size: 6.5, x: margin, y: 22 },
    );
  }
  return document.save();
}
